from __future__ import annotations

from pathlib import Path
import argparse
import sys

# Allows direct script execution:
# python scripts/plot_resolved_bev.py --resolved-json ...
PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from scenario_generator.io.json_io import load_model
from scenario_generator.schema import ResolvedScenario
from scenario_generator.visualization.bev_debug_plot import plot_resolved_bev


def main() -> None:
    parser = argparse.ArgumentParser(description="Plot a resolved scenario JSON in local BEV coordinates.")
    parser.add_argument(
        "--resolved-json",
        required=True,
        help="Path to *.resolved.json generated by scripts/generate_demo.py",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Output PNG path. Default: same filename with .bev.png suffix.",
    )
    parser.add_argument(
        "--every-n-frames",
        type=int,
        default=5,
        help="Draw direction arrows every N frames.",
    )
    parser.add_argument(
        "--show-frame-labels",
        action="store_true",
        help="Show frame indices near sampled arrows.",
    )
    args = parser.parse_args()

    resolved_path = Path(args.resolved_json)
    scenario = load_model(resolved_path, ResolvedScenario)

    if args.output:
        output_path = Path(args.output)
    else:
        output_path = resolved_path.with_suffix("").with_suffix(".bev.png")

    plot_resolved_bev(
        scenario=scenario,
        output_path=output_path,
        every_n_frames=args.every_n_frames,
        show_frame_labels=args.show_frame_labels,
    )

    print(f"Saved BEV debug plot: {output_path}")


if __name__ == "__main__":
    main()
