#!/usr/bin/env python3

"""
build_he_geometry_calibration_v1.py

Build the frozen HE Geometry Calibration V1 lookup surface.

Inputs
------
Two controlled CARLA calibration analyses:

1. Primary side:
   viewpoints 0..180 deg

2. Opposite side:
   viewpoints 210..345 deg

Each source contains pose_medians.csv generated by:
    analyze_geometry_calibration_grid_v1.py

Output
------
Compressed NPZ containing:

    distance_values
    angle_values

    width_scale
    height_scale
    bottom_offset_px
    cx_offset_px

Shape of every correction surface:
    [distance_index, angle_index]

Expected final grid:
    5 distances x 16 viewpoints = 80 knots
"""

import argparse
import csv
import json
from pathlib import Path

import numpy as np


EXPECTED_DISTANCES = [
    10.0,
    15.0,
    20.0,
    30.0,
    40.0,
]

EXPECTED_ANGLES = [
    0.0,
    15.0,
    30.0,
    45.0,
    60.0,
    90.0,
    120.0,
    150.0,
    180.0,
    210.0,
    240.0,
    270.0,
    300.0,
    315.0,
    330.0,
    345.0,
]


def load_pose_csv(path):

    path = Path(path)

    rows = []

    with path.open(
        "r",
        encoding="utf-8",
        newline="",
    ) as f:

        reader = csv.DictReader(f)

        for row in reader:

            rows.append({
                "pose_id":
                    str(row["pose_id"]),

                "distance_m":
                    float(
                        row[
                            "requested_distance_m"
                        ]
                    ),

                "angle_deg":
                    float(
                        row[
                            "requested_viewpoint_deg"
                        ]
                    ),

                "width_scale":
                    float(
                        row[
                            "width_scale_median"
                        ]
                    ),

                "height_scale":
                    float(
                        row[
                            "height_scale_median"
                        ]
                    ),

                "bottom_offset_px":
                    float(
                        row[
                            "bottom_offset_median_px"
                        ]
                    ),

                "cx_offset_px":
                    float(
                        row[
                            "cx_offset_median_px"
                        ]
                    ),
            })

    if not rows:

        raise RuntimeError(
            f"No calibration rows found: {path}"
        )

    return rows


def check_axis(
    actual,
    expected,
    name,
):

    actual = sorted(
        float(v)
        for v in actual
    )

    expected = sorted(
        float(v)
        for v in expected
    )

    if len(actual) != len(expected):

        raise RuntimeError(
            f"{name} count mismatch: "
            f"actual={actual}, expected={expected}"
        )

    for a, e in zip(
        actual,
        expected,
    ):

        if abs(a - e) > 1e-6:

            raise RuntimeError(
                f"{name} mismatch: "
                f"actual={actual}, expected={expected}"
            )


def main():

    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--primary",
        required=True,
        help=(
            "pose_medians.csv for "
            "0..180 degree calibration"
        ),
    )

    parser.add_argument(
        "--opposite",
        required=True,
        help=(
            "pose_medians.csv for "
            "210..345 degree calibration"
        ),
    )

    parser.add_argument(
        "--output",
        required=True,
    )

    args = parser.parse_args()

    primary_path = Path(
        args.primary
    )

    opposite_path = Path(
        args.opposite
    )

    output_path = Path(
        args.output
    )

    rows = (
        load_pose_csv(
            primary_path
        )
        +
        load_pose_csv(
            opposite_path
        )
    )

    # ============================================================
    # Duplicate protection
    # ============================================================

    lookup = {}

    for row in rows:

        key = (
            float(
                row[
                    "distance_m"
                ]
            ),
            float(
                row[
                    "angle_deg"
                ]
            ),
        )

        if key in lookup:

            raise RuntimeError(
                "Duplicate calibration knot: "
                f"{key}"
            )

        lookup[key] = row

    distances = sorted({
        key[0]
        for key
        in lookup.keys()
    })

    angles = sorted({
        key[1]
        for key
        in lookup.keys()
    })

    check_axis(
        distances,
        EXPECTED_DISTANCES,
        "distance axis",
    )

    check_axis(
        angles,
        EXPECTED_ANGLES,
        "angle axis",
    )

    expected_count = (
        len(
            EXPECTED_DISTANCES
        )
        *
        len(
            EXPECTED_ANGLES
        )
    )

    if len(lookup) != expected_count:

        missing = []

        for d in EXPECTED_DISTANCES:

            for a in EXPECTED_ANGLES:

                if (
                    float(d),
                    float(a),
                ) not in lookup:

                    missing.append(
                        (
                            d,
                            a,
                        )
                    )

        raise RuntimeError(
            "Incomplete calibration grid. "
            f"Have {len(lookup)}, "
            f"expected {expected_count}. "
            f"Missing: {missing}"
        )

    distance_values = np.asarray(
        EXPECTED_DISTANCES,
        dtype=np.float64,
    )

    angle_values = np.asarray(
        EXPECTED_ANGLES,
        dtype=np.float64,
    )

    shape = (
        len(
            distance_values
        ),
        len(
            angle_values
        ),
    )

    width_scale = np.zeros(
        shape,
        dtype=np.float64,
    )

    height_scale = np.zeros(
        shape,
        dtype=np.float64,
    )

    bottom_offset_px = np.zeros(
        shape,
        dtype=np.float64,
    )

    cx_offset_px = np.zeros(
        shape,
        dtype=np.float64,
    )

    for di, distance in enumerate(
        distance_values
    ):

        for ai, angle in enumerate(
            angle_values
        ):

            row = lookup[
                (
                    float(
                        distance
                    ),
                    float(
                        angle
                    ),
                )
            ]

            width_scale[
                di,
                ai,
            ] = row[
                "width_scale"
            ]

            height_scale[
                di,
                ai,
            ] = row[
                "height_scale"
            ]

            bottom_offset_px[
                di,
                ai,
            ] = row[
                "bottom_offset_px"
            ]

            cx_offset_px[
                di,
                ai,
            ] = row[
                "cx_offset_px"
            ]

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    np.savez_compressed(
        output_path,

        schema_version=np.asarray(
            "he_geometry_calibration_v1"
        ),

        distance_values=
            distance_values,

        angle_values=
            angle_values,

        width_scale=
            width_scale,

        height_scale=
            height_scale,

        bottom_offset_px=
            bottom_offset_px,

        cx_offset_px=
            cx_offset_px,
    )

    manifest = {
        "schema_version":
            "he_geometry_calibration_v1",

        "source_primary":
            str(
                primary_path
            ),

        "source_opposite":
            str(
                opposite_path
            ),

        "output_npz":
            str(
                output_path
            ),

        "distance_values_m":
            distance_values.tolist(),

        "angle_values_deg":
            angle_values.tolist(),

        "shape":
            list(
                shape
            ),

        "knot_count":
            int(
                expected_count
            ),

        "interpolation_plan": {
            "distance":
                "linear_clamped",

            "viewpoint":
                "linear_circular",
        },

        "corrections": {
            "box_width":
                "multiply by width_scale",

            "box_height":
                "multiply by height_scale",

            "bottom_y":
                "add bottom_offset_px",

            "cx":
                "add cx_offset_px",
        },

        "notes": [
            (
                "Calibration is applied after "
                "HEPlacement and before rendering."
            ),
            (
                "Renderer and sprite bank are "
                "not modified by this calibration."
            ),
            (
                "Distance outside 10..40 m "
                "is clamped to the measured boundary."
            ),
        ],
    }

    manifest_path = (
        output_path.with_suffix(
            ".json"
        )
    )

    with manifest_path.open(
        "w",
        encoding="utf-8",
    ) as f:

        json.dump(
            manifest,
            f,
            indent=2,
        )

    print()
    print("=" * 88)
    print(
        "HE GEOMETRY CALIBRATION V1 BUILDER"
    )
    print("=" * 88)

    print(
        "Primary rows :",
        len(
            load_pose_csv(
                primary_path
            )
        ),
    )

    print(
        "Opposite rows:",
        len(
            load_pose_csv(
                opposite_path
            )
        ),
    )

    print(
        "Distances    :",
        distance_values.tolist(),
    )

    print(
        "Angles       :",
        angle_values.tolist(),
    )

    print(
        "Surface shape:",
        shape,
    )

    print(
        "Knots        :",
        expected_count,
    )

    print()
    print(
        "Width scale range :",
        f"{width_scale.min():.6f}",
        "to",
        f"{width_scale.max():.6f}",
    )

    print(
        "Height scale range:",
        f"{height_scale.min():.6f}",
        "to",
        f"{height_scale.max():.6f}",
    )

    print(
        "Bottom offset range:",
        f"{bottom_offset_px.min():.4f}",
        "to",
        f"{bottom_offset_px.max():.4f}",
        "px",
    )

    print(
        "CX offset range    :",
        f"{cx_offset_px.min():.4f}",
        "to",
        f"{cx_offset_px.max():.4f}",
        "px",
    )

    print()
    print(
        "Saved:",
        output_path,
    )

    print(
        "Saved:",
        manifest_path,
    )

    print("=" * 88)


if __name__ == "__main__":
    main()