"""
traffic_light_schedule_v1.py

Shared deterministic CARLA traffic-light schedule executor.

Reads the environment sidecar generated by ScenarioGenerator, e.g.:

    signalized_lead_follow_001.environment_v1.json

and applies its traffic-light phases identically for CARLA and HE
conditions.

The helper:
- resolves CARLA traffic lights by actor id,
- saves original state/frozen state,
- freezes scheduled lights,
- applies the requested phase as scenario time advances,
- restores original state during cleanup.
"""

from __future__ import annotations

import csv
import json
import math
from pathlib import Path


def load_environment_json(path):
    path = Path(path)

    with path.open(
        "r",
        encoding="utf-8",
    ) as fp:
        return json.load(fp)


def route_xy_at_progress(
    route_csv,
    target_s_m,
):
    """
    Interpolate the inspected route.csv at a requested
    cumulative route progress.

    Returns:
        (world_x, world_y)
    """

    route_csv = Path(
        route_csv
    )

    rows = []

    with route_csv.open(
        "r",
        encoding="utf-8",
        newline="",
    ) as fp:

        reader = csv.DictReader(
            fp
        )

        for row in reader:

            rows.append(
                (
                    float(
                        row[
                            "route_progress_m"
                        ]
                    ),
                    float(
                        row["x"]
                    ),
                    float(
                        row["y"]
                    ),
                )
            )

    rows.sort(
        key=lambda row:
            row[0]
    )

    if len(rows) < 2:

        raise RuntimeError(
            "Route CSV contains fewer "
            "than two points."
        )

    target_s_m = float(
        target_s_m
    )

    if target_s_m <= rows[0][0]:

        return (
            rows[0][1],
            rows[0][2],
        )

    if target_s_m >= rows[-1][0]:

        return (
            rows[-1][1],
            rows[-1][2],
        )

    for i in range(
        len(rows) - 1
    ):

        s0, x0, y0 = (
            rows[i]
        )

        s1, x1, y1 = (
            rows[i + 1]
        )

        if (
            target_s_m >= s0
            and
            target_s_m <= s1
        ):

            ds = (
                s1 - s0
            )

            if abs(ds) <= 1e-9:
                u = 0.0
            else:
                u = (
                    target_s_m - s0
                ) / ds

            return (
                x0
                + u
                * (
                    x1 - x0
                ),

                y0
                + u
                * (
                    y1 - y0
                ),
            )

    raise RuntimeError(
        "Could not interpolate "
        "route progress."
    )


def traffic_light_reference_locations(
    light,
):
    """
    Prefer CARLA traffic-light stop waypoints.

    The traffic-light actor itself can be several metres
    away from the lane, so the stop waypoint is a much
    better geometric reference.
    """

    locations = []

    if hasattr(
        light,
        "get_stop_waypoints",
    ):

        try:

            stop_waypoints = (
                light
                .get_stop_waypoints()
            )

            if stop_waypoints is not None:

                for waypoint in (
                    stop_waypoints
                ):

                    locations.append(
                        waypoint
                        .transform
                        .location
                    )

        except Exception:
            pass

    if not locations:

        locations.append(
            light
            .get_transform()
            .location
        )

    return locations


def resolve_traffic_light_from_route(
    world,
    environment,
    schedule,
):
    """
    Resolve a traffic light using stable map geometry,
    NOT CARLA's runtime actor ID.

    CARLA actor IDs are regenerated when load_world()
    creates a new world.
    """

    route_info = (
        environment.get(
            "route",
            {}
        )
    )

    route_csv = (
        route_info.get(
            "route_csv"
        )
    )

    route_progress_m = (
        schedule.get(
            "route_progress_m"
        )
    )

    if (
        route_csv is None
        or
        route_progress_m is None
    ):

        return None

    target_x, target_y = (
        route_xy_at_progress(
            route_csv=
                route_csv,

            target_s_m=
                route_progress_m,
        )
    )

    lights = (
        world
        .get_actors()
        .filter(
            "traffic.traffic_light*"
        )
    )

    best_light = None
    best_distance = float(
        "inf"
    )

    for light in lights:

        locations = (
            traffic_light_reference_locations(
                light
            )
        )

        for location in locations:

            distance = math.hypot(
                float(
                    location.x
                )
                - target_x,

                float(
                    location.y
                )
                - target_y,
            )

            if (
                distance
                < best_distance
            ):

                best_distance = (
                    distance
                )

                best_light = (
                    light
                )

    if best_light is None:

        return None

    # Our inspected light was only ~0.59 m from the
    # traced route. A generous threshold protects us
    # from accidentally selecting another intersection.
    if best_distance > 10.0:

        raise RuntimeError(
            "Nearest runtime traffic light "
            "is too far from scheduled "
            "route position: "
            f"{best_distance:.2f} m"
        )

    return (
        best_light,
        best_distance,
    )


def traffic_light_state_from_name(
    carla_module,
    name,
):
    name = str(name).strip().lower()

    mapping = {
        "red":
            carla_module.TrafficLightState.Red,

        "yellow":
            carla_module.TrafficLightState.Yellow,

        "green":
            carla_module.TrafficLightState.Green,

        "off":
            carla_module.TrafficLightState.Off,

        "unknown":
            carla_module.TrafficLightState.Unknown,
    }

    if name not in mapping:
        raise ValueError(
            f"Unsupported traffic-light state: {name!r}"
        )

    return mapping[name]


def traffic_light_state_name(state):
    text = str(state)

    if "." in text:
        text = text.split(".")[-1]

    return text


class TrafficLightScheduleExecutor:
    def __init__(
        self,
        world,
        carla_module,
        environment,
    ):
        self.world = world
        self.carla = carla_module
        self.environment = environment

        self.entries = []
        self.initialized = False

    @classmethod
    def from_json(
        cls,
        world,
        carla_module,
        path,
    ):
        environment = (
            load_environment_json(path)
        )

        return cls(
            world=world,
            carla_module=carla_module,
            environment=environment,
        )

    def initialize(self):
        if self.initialized:
            return

        actor_by_id = {
            int(actor.id): actor
            for actor in (
                self.world
                .get_actors()
                .filter(
                    "traffic.traffic_light*"
                )
            )
        }

        schedules = (
            self.environment
            .get(
                "traffic_lights",
                [],
            )
        )

        for schedule in schedules:

            inspection_light_id = int(
                schedule[
                    "traffic_light_id"
                ]
            )

            # ------------------------------------------------
            # IMPORTANT:
            #
            # CARLA actor IDs are runtime IDs and change after
            # load_world(). Therefore the ID recorded by the
            # route inspector cannot be used as the primary
            # runtime lookup.
            #
            # Resolve the signal from its stable route
            # position instead.
            # ------------------------------------------------

            resolved = (
                resolve_traffic_light_from_route(
                    world=
                        self.world,

                    environment=
                        self.environment,

                    schedule=
                        schedule,
                )
            )

            if resolved is not None:

                (
                    light,
                    match_distance_m,
                ) = resolved

                print(
                    "[traffic light resolve] "
                    f"inspection_id="
                    f"{inspection_light_id} "
                    f"-> runtime_id="
                    f"{int(light.id)} "
                    f"route_match="
                    f"{match_distance_m:.2f} m"
                )

            else:

                # Compatibility fallback for older environment
                # files that do not contain route metadata.
                light = actor_by_id.get(
                    inspection_light_id
                )

                if light is None:

                    available = sorted(
                        actor_by_id.keys()
                    )

                    raise RuntimeError(
                        "Could not resolve scheduled "
                        "traffic light. "
                        f"Inspection ID="
                        f"{inspection_light_id}; "
                        f"runtime IDs="
                        f"{available[:20]}"
                    )

                print(
                    "[traffic light resolve] "
                    f"using runtime-ID fallback: "
                    f"{inspection_light_id}"
                )

            light_id = (
                inspection_light_id
            )

            phases = list(
                schedule.get(
                    "phases",
                    [],
                )
            )

            if not phases:
                raise ValueError(
                    f"Traffic light {light_id} "
                    f"has no phases."
                )

            phases.sort(
                key=lambda row:
                    float(
                        row["start_s"]
                    )
            )

            original_state = (
                light.get_state()
            )

            try:
                original_frozen = bool(
                    light.is_frozen()
                )
            except Exception:
                original_frozen = False

            self.entries.append(
                {
                    "light_id":
                        light_id,

                    "runtime_light_id":
                        int(
                            light.id
                        ),

                    "light":
                        light,

                    "phases":
                        phases,

                    "original_state":
                        original_state,

                    "original_frozen":
                        original_frozen,

                    "last_applied_name":
                        None,
                }
            )

            # Prevent CARLA's normal signal timer from changing
            # the scheduled light underneath the experiment.
            light.freeze(True)

        self.initialized = True

        # Apply t=0 state immediately.
        self.apply(0.0)

    def _phase_for_time(
        self,
        phases,
        t_s,
    ):
        t_s = float(t_s)

        selected = None

        for phase in phases:
            start_s = float(
                phase["start_s"]
            )

            end_s = float(
                phase["end_s"]
            )

            # Half-open interval [start, end).
            if (
                t_s >= start_s
                and
                t_s < end_s
            ):
                selected = phase
                break

        # At the exact final scenario timestamp, use the last
        # phase if t == end_s.
        if selected is None and phases:
            last = phases[-1]

            if abs(
                t_s
                - float(
                    last["end_s"]
                )
            ) <= 1e-6:
                selected = last

        return selected

    def apply(
        self,
        t_s,
    ):
        if not self.initialized:
            self.initialize()

        states = {}

        for entry in self.entries:
            phase = self._phase_for_time(
                entry["phases"],
                t_s,
            )

            if phase is None:
                states[
                    entry["light_id"]
                ] = ""
                continue

            requested_name = str(
                phase["state"]
            )

            requested_state = (
                traffic_light_state_from_name(
                    self.carla,
                    requested_name,
                )
            )

            normalized_name = (
                traffic_light_state_name(
                    requested_state
                )
            )

            if (
                entry[
                    "last_applied_name"
                ]
                != normalized_name
            ):
                entry["light"].set_state(
                    requested_state
                )

                entry[
                    "last_applied_name"
                ] = normalized_name

                print(
                    "[traffic light]",
                    f"inspection_id="
                    f"{entry['light_id']}",
                    f"runtime_id="
                    f"{entry['runtime_light_id']}",
                    "->",
                    normalized_name,
                    f"at t={float(t_s):.2f}s",
                )

            states[
                entry["light_id"]
            ] = normalized_name

        return states

    def primary_state_name(
        self,
        t_s,
    ):
        states = self.apply(
            t_s
        )

        if not states:
            return ""

        first_id = next(
            iter(states)
        )

        return states[
            first_id
        ]

    def restore(self):
        if not self.initialized:
            return

        for entry in self.entries:
            light = entry["light"]

            try:
                light.set_state(
                    entry[
                        "original_state"
                    ]
                )
            except Exception:
                pass

            try:
                light.freeze(
                    entry[
                        "original_frozen"
                    ]
                )
            except Exception:
                pass

        self.initialized = False
